# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep <- function(m, K, lb, ub) {
    .Call(`_hybrid_ep`, m, K, lb, ub)
}

ep_logz <- function(m, K, lb, ub) {
    .Call(`_hybrid_ep_logz`, m, K, lb, ub)
}

rcpparma_hello_world <- function() {
    .Call(`_hybrid_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_hybrid_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_hybrid_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_hybrid_rcpparma_bothproducts`, x)
}

